FORMAT: 1A

# Expense Tracker

This is the API for an Expense Tracker application that allows users to track their own expenses through multiple wallets.

# Group Auth

Resources related to the authentication in the API.

## User Register [/register]

### Register a New User [POST]

This action registers a new user. It takes a JSON object containing the user's information.

+ displayName (string) - The user name that will be displayed in the application
+ email (string) - The user's email that will be used for login and optional notifications
+ phone (string) - The user's phone number that will be used for optional notifications
+ password (string) - The user's password that will be used for login
+ totalFundsCurrencyCode (string) - The Code of the currency used to display user's total funds

+ Request (application/json)
  
        {
            "displayName": "John Smith",
            "email": "john.smith@mail.com",
            "phone": "+5511912345678",
            "password": "mySecretPassword",
            "totalFundsCurrencyCode": "USD"
        }

+ Response 201 (application/json)

    + Body

            {
                "success": true,
                "data": {
                    "email": "john.smith@mail.com"
                }
            }

## User Login [/login]

### Login a User [POST]

This action lets a user login into the application. It takes a JSON object containing the user's email and password.

+ email (string) - The user's email.
+ password (string) - The user's password.

+ Request (application/json)

        {
            "email": "john.smith@mail.com",
            "password": "mySecretPassword"
        }

+ Response 200 (application/json)
    
    + Body

            {
                "success": true,
                "data": {
                    "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwiZGlzcGxheU5hbWUiOiJKb2huIFNtaXRoIiwiZW1haWwiOiJqb2huLnNtaXRoQG1haWwuY29tIiwicGhvbmUiOiIrNTUxMTkxMjM0NTY3OCIsImlhdCI6MTUxNjIzOTAyMn0.rn20ARVCpohOt835Y3LRZC2gq9UDlqFmvVKrmNjsJJs"
                }
            }

# Group User Account

## User Account [/account]

### Update User Account Information [PUT]

This action let's the user update their information (displayed name, email, phone number, total funds currency code).

+ displayName (string) - The user name that will be displayed in the application
+ email (string) - The user's email that will be used for login and optional notifications
+ phone (string) - The user's phone number that will be used for optional notifications

+ Request (application/json)
  
        {
            "displayName": "John Smith New Display Name",
            "email": "john.smith@mail.com",
            "phone": "+5511912345678",
            "totalFundsCurrencyCode": "USD"
        }

+ Response 200 (application/json)

    + Body

            {
                "success": true,
                "data": {
                    "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwiZGlzcGxheU5hbWUiOiJKb2huIFNtaXRoIiwiZW1haWwiOiJqb2huLnNtaXRoQG1haWwuY29tIiwicGhvbmUiOiIrNTUxMTkxMjM0NTY3OCIsImlhdCI6MTUxNjIzOTAyMn0.rn20ARVCpohOt835Y3LRZC2gq9UDlqFmvVKrmNjsJJs"
                }
            }

### Delete a User Account [DELETE]

This action marks an user account for deletion requiring delete confirmation via email.

+ Request (application/json)
    
    + Headers
        
            Authorization: Bearer {user_jwt}

+ Response 202 (application/json)

    + Body

            {
                "success": true
            }


## User Password [/account/password]

### Reset Forgotten Password [POST]

This action let's a user who forgot their password reset it via email.

+ userEmail (string) - The email of the user that forgot password

+ Request (application/json)

        {
            "userEmail": "john.smith@mail.com"
        }

+ Response 202 (application/json)

    + Body

            {
                "success": true,
                "data": {
                    "userEmail": "john.smith@mail.com"
                }
            }

### Change User Password [PATCH]

This action let's a logged in user change their current password.

+ oldPassword (string) - User's old password
+ newPassword (string) - User's new password

+ Request (application/json)
  
        {
            "oldPassword": "mySecretPassword",
            "newPassword": "myUpdatedPassword"
        }

+ Response 200 (application/json)

    + Body

            {
                "success": true
            }

# Group Currencies

## Currencies [/currencies]

### Get All Currencies [GET]

This action returns all categories available.

This action returns all user wallets.

+ Request (application/json)
    
    + Headers
        
            Authorization: Bearer {user_jwt}

+ Response 200 (application/json)

    + Body

            {
                "success": true,
                "data": [
                    { "code": "USD", "symbol": "$", "decimalDigits": 2 },
                    { "code": "CAD", "symbol": "$", "decimalDigits": 2 },
                    { "code": "BRL", "symbol": "R$", "decimalDigits": 2 },
                    ...
                ]
            }


# Group Wallets

## User Wallets [/wallet]

### Get All User Wallets [GET]

This action returns all user wallets.

+ Request (application/json)
    
    + Headers
        
            Authorization: Bearer {user_jwt}

+ Response 200 (application/json)

    + Body

            {
                "success": true,
                "data": [
                    { 
                        "id": 0,
                        "name": "Personal Wallet",
                        "description": "Wallet for my personal expenses",
                        "funds": 100000,
                        "currencyCode": "USD",
                        "decimalDigits": 2
                    },
                    { 
                        "id": 1,
                        "name": "Savings",
                        "description": "Wallet for savings",
                        "funds": 2500000,
                        "currencyCode": "USD",
                        "decimalDigits": 2
                    }
                ]
            }

### Create New Wallet [POST]

This action creates a new user wallet.

+ name (string) The wallet's name.
+ description (string) The wallet's description.
+ currencyCode (string) The currency code to be used for the wallet's funds.
+ startingFunds (number) The starting funds of the wallet.

+ Request (application/json)
    
    + Headers
        
            Authorization: Bearer {user_jwt}
    
    + Body

            {
                "name": "Wallet's Name",
                "description": "Wallet's Description",
                "currencyCode": "CAD",
                "startingFunds": 0
            }

+ Response 201 (application/json)

    + Body

            {
                "success": true,
                "data": {
                    "id": 3,
                    "name": "Wallet's Name",
                    "description": "Wallet's Description",
                    "funds": 0,
                    "currencyCode": "CAD",
                    "decimalDigits": 2
                }
            }

## User Specific Wallet [/wallet/{wallet_id}]

+ Parameters
    + wallet_id: 3 (required, number) - ID of the wallet to perform the action on.

### Get Single User Wallet [GET]

This action returns a single user wallet

+ Request (application/json)
    
    + Headers
        
            Authorization: Bearer {user_jwt}

+ Response 200 (application/json)

    + Body

            {
                "success": true,
                "data": {
                    "id": 3,
                    "name": "Wallet's Name",
                    "description": "Wallet's Description",
                    "funds": 0,
                    "currencyCode": "CAD",
                    "decimalDigits": 2
                }
            }

### Update Wallet Information [PUT]

This actions let's the user change the name or description of a wallet.

+ name (string) The wallet's name.
+ description (string) The wallet's description.

+ Request (application/json)
    
    + Headers
        
            Authorization: Bearer {user_jwt}
    
    + Body

            {
                "name": "Wallet's Name",
                "description": "Wallet's Description"
            }

+ Response 200 (application/json)

    + Body

            {
                "success": true,
                "data": {
                    "id": 3,
                    "name": "Updated Wallet Name",
                    "description": "Wallet's Description",
                    "funds": 0,
                    "currencyCode": "CAD",
                    "decimalDigits": 2
                }
            }

### Delete Wallet [DELETE]

This action let's the user delete a wallet and all related information.

+ Request (application/json)
    
    + Headers
        
            Authorization: Bearer {user_jwt}

+ Response 200 (application/json)

    + Body

            {
                "success": true
            }

# Group Categories

## Expense Categories [/categories]

### Get All User's Categories [GET]

This action returns all user's expense categories.

+ Request (application/json)
    
    + Headers
        
            Authorization: Bearer {user_jwt}

+ Response 200 (application/json)

    + Body

            {
                "success": true,
                "data": [
                    { 
                        "id": 0,
                        "name": "Food",
                        "description": "Category for all Food related transactions"
                    },
                    { 
                        "id": 1,
                        "name": "Rent",
                        "description": "Category for all rent payments"
                    }
                ]
            }

### Create New Category [POST]

This action creates a new expense category for the user.

+ name (string) The category's name.
+ description (string) The category's description.

+ Request (application/json)
    
    + Headers
        
            Authorization: Bearer {user_jwt}
    
    + Body

            {
                "name": "Gas",
                "description": "Expenses related to fuel for my car"
            }

+ Response 201 (application/json)

    + Body

            {
                "success": true,
                "data": {
                    "id": 2,
                    "name": "Gas",
                    "description": "Expenses related to fuel for my car"
                }
            }

## Specific Expense Category [/categories/{category_id}]

+ Parameters
    + category_id: 2 (required, number) - ID of the category to perform the action on.

### Get Single Expense Category [GET]

This action returns a single user's expense category.

+ Request (application/json)
    
    + Headers
        
            Authorization: Bearer {user_jwt}

+ Response 200 (application/json)

    + Body

            {
                "success": true,
                "data": {
                    "id": 2,
                    "name": "Gas",
                    "description": "Expenses related to fuel for my car"
                }
            }

### Update Category Information [PUT]

This actions let's the user change the name or description of a category.

+ name (string) The category's name.
+ description (string) The category's description.

+ Request (application/json)
    
    + Headers
        
            Authorization: Bearer {user_jwt}
    
    + Body

            {
                "name": "Updated Category Name",
                "description": "Expenses related to fuel for my car"
            }

+ Response 200 (application/json)

    + Body

            {
                "success": true,
                "data": {
                    "id": 2,
                    "name": "Updated Category Name",
                    "description": "Expenses related to fuel for my car"
                }
            }

### Delete Category [DELETE]

This action let's the user delete a category and all related information.

+ Request (application/json)
    
    + Headers
        
            Authorization: Bearer {user_jwt}

+ Response 200 (application/json)

    + Body

            {
                "success": true
            }

# Group Tags

## Expense Tags [/tags]

### Get All User's Tags [GET]

This action returns all user's expense tags. Tags differ from categories because expenses can have multiple tags and only a single category, also tags are optional while category is required for an expense.

+ Request (application/json)
    
    + Headers
        
            Authorization: Bearer {user_jwt}

+ Response 200 (application/json)

    + Body

            {
                "success": true,
                "data": [
                    { 
                        "id": 0,
                        "name": "Friend's Payment"
                    },
                    { 
                        "id": 1,
                        "name": "Check Later"
                    }
                ]
            }

### Create New Tag [POST]

This action creates a new expense tag for the user.

+ name (string) The tag's name.

+ Request (application/json)
    
    + Headers
        
            Authorization: Bearer {user_jwt}
    
    + Body

            {
                "name": "Cash Payment"
            }

+ Response 201 (application/json)

    + Body

            {
                "success": true,
                "data": {
                    "id": 2,
                    "name": "Cash Payment"
                }
            }

## Specific Expense Tag [/tags/{tag_id}]

+ Parameters
    + tag_id: 2 (required, number) - ID of the tag to perform the action on.

### Get Single Expense Tag [GET]

This action returns a single user's expense tag.

+ Request (application/json)
    
    + Headers
        
            Authorization: Bearer {user_jwt}

+ Response 200 (application/json)

    + Body

            {
                "success": true,
                "data": {
                    "id": 2,
                    "name": "Cash Payment"
                }
            }

### Update Tag Information [PUT]

This actions let's the user change the name of a tag.

+ name (string) The tag's name.

+ Request (application/json)
    
    + Headers
        
            Authorization: Bearer {user_jwt}
    
    + Body

            {
                "name": "Updated Tag Name",
            }

+ Response 200 (application/json)

    + Body

            {
                "success": true,
                "data": {
                    "id": 2,
                    "name": "Updated Tag Name"
                }
            }

### Delete Tag [DELETE]

This action let's the user delete a tag.

+ Request (application/json)
    
    + Headers
        
            Authorization: Bearer {user_jwt}

+ Response 200 (application/json)

    + Body

            {
                "success": true
            }
