openapi: '3.0.3'
info:
  title: Expense Tracker API
  description: This is the API for an Expense Tracker application that allows users to track their own expenses through multiple wallets and supports phone and email alerts.
  version: '1.0'
servers:
  - url: http://localhost:3000
paths:
  /auth/register:
    $ref: './paths/register.yaml'
  /auth/login:
    $ref: './paths/login.yaml'
  /auth/resend-confirmation-email:
    $ref: './paths/emailConfirmationResend.yaml'
  /auth/email-confirmation/{jwt}:
    $ref: './paths/emailConfirmation.yaml'
  /currencies:
    $ref: './paths/currencies.yaml'
  /account:
    $ref: './paths/account.yaml'
  /account/password:
    $ref: './paths/accountPassword.yaml'
  /wallets:
    $ref: './paths/wallets.yaml'
  /wallets/{id}:
    $ref: './paths/wallet.yaml'
  /categories:
    $ref: './paths/categories.yaml'
  /categories/{id}:
    $ref: './paths/category.yaml'
  /tags:
    $ref: './paths/tags.yaml'
  /tags/{id}:
    $ref: './paths/tag.yaml'
  /alerts:
    $ref: './paths/alerts.yaml'
  /alerts/{id}:
    $ref: './paths/alert.yaml'
  /transactions:
    $ref: './paths/transactions.yaml'
  /transactions/{id}:
    $ref: './paths/transaction.yaml'
components:
  schemas:
    $ref: './schemas/index.yaml'
  requestBodies:
    $ref: './requestBodies/index.yaml'
  parameters:
    authorization:
      $ref: './parameters/authorization.yaml'
    resource_id:
      $ref: './parameters/resource_id.yaml'
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: Auth
  - name: Account
  - name: Currencies
  - name: Wallets
  - name: Categories
  - name: Tags
  - name: Alerts
  - name: Transactions